### PR TITLE
Broken image link fix for production app.

### PR DESCRIPTION
**Pull request by AlexChalk**
An attempt to solve the problem with image links at `/photos` breaking after a while.

### CODE REVIEW

**Comment by dbugsy** [comment]
Could be good to get some more info on this. Why are you making this change, is there an issue you can reference? It seems very straightforward, but is it a genuine solution, or is this just sticking a bandaid on?

**Comment by enonnai** [comment]
Yes I was about to write this PR may require a description so that we can test it properly.

**Comment by AlexChalk** [comment]
It's difficult to troubleshoot this issue without a staging area, so it was a bit of a guess. I'm trying to resolve the issue where links to images on the production site break after a period of time.

**Comment by AlexChalk** [comment]
The weekend challenge has taught me that my solution would not have worked.

**Pull request closed without merging**
