### PR TITLE
Modeling users

### PR DESCRIPTION
**Pull request by adamerdemer**
Added basic User model

### CODE REVIEW

**Comment by JessicaBarclay** [comment]
:shipit:

**Comment by chrisjmit** [comment]
:shipit:

**Comment by FiddlersCode** [comment]
Will any of this change once we go to Postgres?

**Review by AlexChalk — CHANGES_REQUESTED** [review]
Guys, can you explain the change on line 13 of `db/schema.rb`? Also, I think there should be a user controller as well?

p.s. fix indentation in spec file.

**Comment by Robert-G-J** [comment]
Line 13 in `db/schema.rb` is autogenerated. The model was created using Rails' terminal commands and therefore no opinion has been expressed regarding Postgres choice.

**Comment by adamerdemer** [comment]
User controller is in signing-up branch. Refer to there.

**Pull request closed without merging**
