### PR TITLE
Fix sign-in test bug

### PR DESCRIPTION
**Pull request by AlexChalk**

### CODE REVIEW

**Comment by JessicaBarclay** [comment]
thanks guys :shipit:

**Comment by adamerdemer** [comment]
:shipit:

**Comment by Robert-G-J** [comment]
:shipit: get that out

**Comment by enonnai** [comment]
:shipit:

**Review by danielemanuel — APPROVED** [review]
:shipit: :

**Review by JessicaBarclay — COMMENTED** [review]
good to ship

**Pull request merged**
