### PR TITLE
adds method to show local time

### PR DESCRIPTION
**Pull request by sophieklm**
fixes local time zone rendering

### CODE REVIEW

**Review by AlexChalk — APPROVED** [review]
:shipit:

**Review by chrisjmit — APPROVED** [review]
:shipit: 
Great work!

**Review by anaalta — APPROVED** [review]
:shipit:

**Comment by dbugsy** [comment]
:shipit:

**Comment by dbugsy** [comment]
The build has passed (click on 'details') but github is being weird. Looks fine to me.

**Comment by JessicaBarclay** [comment]
awesome :shipit:

**Comment by enonnai** [comment]
:ship: it

**Pull request merged**
