### PR TITLE
Photos

### PR DESCRIPTION
**Pull request by AlexChalk**
Add ability to upload photos from local machine to site

### CODE REVIEW

**Comment by dbugsy** [comment]
:shipit: :shipit:

**Comment by JessicaBarclay** [comment]
:shipit:

**Comment by chrisjmit** [comment]
:shipit:

**Review by chrisjmit — APPROVED** [review]

**Review by axcochrane — COMMENTED** [review]
Hey guys - looks good.

Miles and I are working on the album feature today. We can see that there's a few deletions relating to the album view, and some album specs.  

Do we have to remove them, or should Miles and I build again from scratch?

Thanks!
Sandy

**Pull request merged**
