### PR TITLE
Readds feature and unit tests for app/helpers/post_helper.rb

### PR DESCRIPTION
**Pull request by enonnai**
Hi everyone, I just created a branch from the current master to add the feature unit test I wrote for a Helper method Simon and I worked on for the 'click on link' ticket which is in 'done', as they were accidentally deleted. The tests have been amended so to compile with the latest changes. Thanks.

### CODE REVIEW

**Review by JessicaBarclay — APPROVED** [review]
Tests passing, looks good to merge :shipit:

**Review by dbugsy — APPROVED** [review]
:shipit: :shipit:

**Review by axcochrane — APPROVED** [review]
:shipit:

**Comment by axcochrane** [comment]
hey @enonnai - miles and I just reviewed. looks good to merge. Thanks!

**Comment by enonnai** [comment]
Thank you all

**Pull request merged**
