### PR TITLE
Navbar and basic UX changes

### PR DESCRIPTION
**Pull request by chrisjmit**
To test, clone repo and run localhost.
See commits and files changed for detailed changes.
Aiming to get this through so everyone has an updated nav operating today.
We'll submit a further pull request for other formatting changes this afternoon.
[](url)
Thanks. Cristina & Chris

### CODE REVIEW

**Comment by chrisjmit** [comment]
screen shot 2017-06-02 at 13 52 00

**Review by axcochrane — APPROVED** [review]
:shipit:

**Review by FiddlersCode — CHANGES_REQUESTED** [review]
Nice work, guys!  A couple things:

1. /posts is not working for me - this may be a DB issue although I've run the migration again.  Check that it works on someone else's machine 
image

2. /photos page: can you change the link to new photos to a button?  (This will break some tests.)

3. /users and /users show: also change links to buttons

4. Would be great if login/signup buttons disappear from navbar when user is logged in but I realise this may be rather complicated so it's more of a nice-to-have than an essential.

**Comment by anaalta** [comment]
I agree with Paula's comments regarding replacing links with buttons. But functionally & visually it's fine, so :shipit:

**Review by anaalta — APPROVED** [review]

**Comment by dvidgry** [comment]
:shipit: !

**Comment by enonnai** [comment]
Thanks for your feedback guys, Chris and I are looking into Paula's bullet points.

**Comment by chrisjmit** [comment]
@pmuldoon86 @enonnai
1. unsure m'fraid, working across others. latest rake db:migrate on master?
2. & 3. felt our remit was more of a nav bar thing, but willing to try and make these changes now
four(number not working). feel it's a bit of a nice to have, we'll try and do this in the next pull request

**Review by dbugsy — APPROVED** [review]
:shipit: :shipit:

**Comment by dbugsy** [comment]
Incidentally I did not experience the issue that Paula found, it seemed to work fine on my machine. However that does not mean that it is an issue purely for Paula's machine (there may be other machines that would have the same issue, for example). I wonder if the tests are also failing on Paula's machine? If not, maybe we could add a test that covers exactly the actions needed to duplicate the issue for Paula.

**Pull request merged**
