### PR TITLE
Auto-Deploy Changes

### PR DESCRIPTION
**Pull request by AlexChalk**
`.travis.yml` was previously configured to deploy to Heroku, but was failing due to invalid credentials.

This PR removes that responsibility from travis—I have enabled the same feature directly in Heroku instead.

I think this is a better solution, as it means nobody has to make their heroku auth_token publicly available on github. Heroku will still wait for all builds to pass CI tests before deploying.

capture d ecran 2017-06-02 08 18 09
Settings changed are in `ace-book/deploy` on heroku.

### CODE REVIEW

**Review by dbugsy — APPROVED** [review]
Not really anything I can review here, as the changes will all be made in heroku. Sounds like a reasonable solution, though, since the master branch is protected.

**Comment by dbugsy** [comment]
:shipit: :shipit:

**Comment by chrisjmit** [comment]
:shipit: @adc17 it should have been an encrypted auth_token? Seems a good solution

**Review by axcochrane — APPROVED** [review]

**Comment by axcochrane** [comment]
@adc17 :shipit:

**Pull request merged**
