### PR TITLE
Remove photo files mistakenly added to master

### PR DESCRIPTION
**Pull request by AlexChalk**

### CODE REVIEW

**Comment by JessicaBarclay** [comment]
:shipit:

**Comment by FiddlersCode** [comment]
:shipit:

**Comment by JessicaBarclay** [comment]
Hi Alex were there any gems that need removing? They are being listed in Travis(paperclip), not sure if it is a problem at present but may be better to remove them

**Comment by FiddlersCode** [comment]
Alex, can you check with me and @axcochrane before merging?  We have just made your failing test a pending test

**Comment by dbugsy** [comment]
Failures:

  1) posts are visible starting with the newest one one can see a posts starting with the latest
     Failure/Error: click_link "New Post"

     Capybara::ElementNotFound:
       Unable to find link "New Post"
     # ./spec/web_helpers.rb:4:in `create_a_post'
     # ./spec/features/posts_ordered_from_newest_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.84657 seconds (files took 2.54 seconds to load)
13 examples, 1 failure

**Comment by AlexChalk** [comment]
@ddosque we weren't working on that yesterday.

**Comment by AlexChalk** [comment]
@JessicaBarclay removed paperclip

**Comment by AlexChalk** [comment]
@pmuldoon86 of course

**Comment by dbugsy** [comment]
No more red tests to master please

**Comment by AlexChalk** [comment]
Ok now getting some horrible 'db does not exist' style error messages. i don't think we can be responsible for all of this—there are no failing tests in the branch we're working on at present.

**Comment by AlexChalk** [comment]
Right, scrap this, will make a new PR.

**Pull request closed without merging**
