### PR TITLE
Posts belong to users

### PR DESCRIPTION
**Pull request by sophieklm**
Assigns one to many relationship between users and posts, and fixes a bunch of failing tests caused by this change. 
Will require db drop as existing users won't have the relationship assigned and will cause error. 
Renders user email on post page. 

rake db:drop
rake db:create
rake db:migrate

### CODE REVIEW

**Comment by enonnai** [comment]
@sophieklm @Robert-G-J I got an error after dropping:
```~/Projects/acebook/acebook-remote-april-2017 $ rake db:drop
rakePG::ObjectInUse: ERROR:  database "acebook_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "acebook_development"
Couldn't drop database 'acebook_development'
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "acebook_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "acebook_development"

PG::ObjectInUse: ERROR:  database "acebook_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.

Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)```

**Comment by axcochrane** [comment]
@sophieklm - happy to review, looks like it has conflicts relating to what you were talking about in the slack thread. I have no idea what factories do tbh :S  -  give us a shout when resolved and miles and I will review

**Comment by Robert-G-J** [comment]
Hey @enonnai it looks from your error message that your db hasn't dropped. I'm not sure that's caused by the branch but is something local to your machine- would it be okay to try changing branch and trying to drop again? 🙏 I'd be super interested to see what happens! :)

**Review by milesillsley — APPROVED** [review]
:shipit:

**Comment by enonnai** [comment]
@Robert-G-J I had my server running on another terminal tab :man_facepalming: ! I was able to test now, all looks good to me :shipit:

**Pull request merged**
